services:
  db:
    image: postgres:15
    container_name: postgres_cpu-motherboard-compatibility
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_cpu-motherboard-compatibility
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3001:5001"
    depends_on:
      - db
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_cpu-motherboard-compatibility
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db_data:
    external: true
    name: cpu-motherboard-compatibility_db_data
